---
driver:
  name: vagrant
  provider: vmware_fusion

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6

suites:
  - name: server
    data_bags_path: test/integration/data_bags
    run_list:
      - recipe[sensu-handlers::default]
    attributes:
      sensu-handlers:
        default_handlers:
          - sensu-handlers::mailer
        teams:
          test:
            notification_email: 'jacob.royal@buckle.com'
      sensu:
        use_ssl: false
        use_embedded_ruby: true
        rabbitmq:
          port: 5672
